/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as LidarRouteImport } from './routes/lidar'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as UlpinRouteImport } from './routes/ulpin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const LidarRoute = LidarRouteImport.update({
  id: '/lidar',
  path: '/lidar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const UlpinRoute = UlpinRouteImport.update({
  id: '/ulpin',
  path: '/ulpin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/buildings': typeof BuildingsRoute
  '/emergency': typeof EmergencyRoute
  '/lidar': typeof LidarRoute
  '/review': typeof ReviewRoute
  '/solar': typeof SolarRoute
  '/ulpin': typeof UlpinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/buildings': typeof BuildingsRoute
  '/emergency': typeof EmergencyRoute
  '/lidar': typeof LidarRoute
  '/review': typeof ReviewRoute
  '/solar': typeof SolarRoute
  '/ulpin': typeof UlpinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/audit': typeof AuditRoute
  '/buildings': typeof BuildingsRoute
  '/emergency': typeof EmergencyRoute
  '/lidar': typeof LidarRoute
  '/review': typeof ReviewRoute
  '/solar': typeof SolarRoute
  '/ulpin': typeof UlpinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/audit'
    | '/buildings'
    | '/emergency'
    | '/lidar'
    | '/review'
    | '/solar'
    | '/ulpin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/audit'
    | '/buildings'
    | '/emergency'
    | '/lidar'
    | '/review'
    | '/solar'
    | '/ulpin'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/audit'
    | '/buildings'
    | '/emergency'
    | '/lidar'
    | '/review'
    | '/solar'
    | '/ulpin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuditRoute: typeof AuditRoute
  BuildingsRoute: typeof BuildingsRoute
  EmergencyRoute: typeof EmergencyRoute
  LidarRoute: typeof LidarRoute
  ReviewRoute: typeof ReviewRoute
  SolarRoute: typeof SolarRoute
  UlpinRoute: typeof UlpinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lidar': {
      id: '/lidar'
      path: '/lidar'
      fullPath: '/lidar'
      preLoaderRoute: typeof LidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulpin': {
      id: '/ulpin'
      path: '/ulpin'
      fullPath: '/ulpin'
      preLoaderRoute: typeof UlpinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuditRoute: AuditRoute,
  BuildingsRoute: BuildingsRoute,
  EmergencyRoute: EmergencyRoute,
  LidarRoute: LidarRoute,
  ReviewRoute: ReviewRoute,
  SolarRoute: SolarRoute,
  UlpinRoute: UlpinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
